package seed

import (
	"gorm.io/gorm"
	"master-indonesian-territory/entities"
)

func RegencySeed(DB *gorm.DB) error {
	regencies := []*entities.Regency{
		{ID: 1, Name: "Kabupaten Aceh Barat", ProvinceID: 20},
		{ID: 2, Name: "Kabupaten Aceh Barat Daya", ProvinceID: 20},
		{ID: 3, Name: "Kabupaten Aceh Besar", ProvinceID: 20},
		{ID: 4, Name: "Kabupaten Aceh Jaya", ProvinceID: 20},
		{ID: 5, Name: "Kabupaten Aceh Selatan", ProvinceID: 20},
		{ID: 6, Name: "Kabupaten Aceh Singkil", ProvinceID: 20},
		{ID: 7, Name: "Kabupaten Aceh Tamiang", ProvinceID: 20},
		{ID: 8, Name: "Kabupaten Aceh Tengah", ProvinceID: 20},
		{ID: 12, Name: "Kabupaten Agam", ProvinceID: 29},
		{ID: 13, Name: "Kabupaten Alor", ProvinceID: 22},
		{ID: 14, Name: "Kota Ambon", ProvinceID: 18},
		{ID: 15, Name: "Kabupaten Asahan", ProvinceID: 31},
		{ID: 16, Name: "Kabupaten Asmat", ProvinceID: 23},
		{ID: 17, Name: "Kota Batam", ProvinceID: 16},
		{ID: 18, Name: "Kabupaten Badung", ProvinceID: 1},
		{ID: 19, Name: "Kabupaten Balangan", ProvinceID: 13},
		{ID: 20, Name: "Kota Balikpapan", ProvinceID: 15},
		{ID: 21, Name: "Kota Banda Aceh", ProvinceID: 20},
		{ID: 22, Name: "Kota Bandar Lampung", ProvinceID: 17},
		{ID: 23, Name: "Kabupaten Bandung", ProvinceID: 9},
		{ID: 24, Name: "Kota Bandung", ProvinceID: 9},
		{ID: 25, Name: "Kabupaten Banggai", ProvinceID: 26},
		{ID: 26, Name: "Kabupaten Banggai Kepulauan", ProvinceID: 26},
		{ID: 27, Name: "Kabupaten Bangka", ProvinceID: 2},
		{ID: 28, Name: "Kabupaten Bangka Barat", ProvinceID: 2},
		{ID: 29, Name: "Kabupaten Bangka Selatan", ProvinceID: 2},
		{ID: 30, Name: "Bangka Tengah", ProvinceID: 2},
		{ID: 31, Name: "Bangkalan", ProvinceID: 11},
		{ID: 32, Name: "Bangli", ProvinceID: 1},
		{ID: 33, Name: "Kota Banjar", ProvinceID: 9},
		{ID: 34, Name: "Kabupaten Banjar", ProvinceID: 13},
		{ID: 35, Name: "Kota Banjarbaru", ProvinceID: 13},
		{ID: 36, Name: "Kota Banjarmasin", ProvinceID: 13},
		{ID: 37, Name: "Kabupaten Banjarnegara", ProvinceID: 10},
		{ID: 38, Name: "Bantaeng", ProvinceID: 25},
		{ID: 39, Name: "Bantul", ProvinceID: 5},
		{ID: 40, Name: "Kabupaten Banyuasin", ProvinceID: 12},
		{ID: 41, Name: "Kabupaten Banyumas", ProvinceID: 10},
		{ID: 42, Name: "Kabupaten Banyuwangi", ProvinceID: 11},
		{ID: 43, Name: "Kabupaten Barito Kuala", ProvinceID: 13},
		{ID: 44, Name: "Kabupaten Barito Selatan", ProvinceID: 14},
		{ID: 45, Name: "Kabupaten Barito Timur", ProvinceID: 14},
		{ID: 46, Name: "Kabupaten Barito Utara", ProvinceID: 14},
		{ID: 47, Name: "Kabupaten Barru", ProvinceID: 25},
		{ID: 48, Name: "Kabupaten Batang", ProvinceID: 10},
		{ID: 49, Name: "Kabupaten Batang Hari", ProvinceID: 8},
		{ID: 50, Name: "Kota Batu", ProvinceID: 11},
		{ID: 51, Name: "Kabupaten Bekasi", ProvinceID: 9},
		{ID: 52, Name: "Kota Bekasi", ProvinceID: 9},
		{ID: 53, Name: "Kabupaten Belitung", ProvinceID: 2},
		{ID: 54, Name: "Kabupaten Belitung Timur", ProvinceID: 2},
		{ID: 55, Name: "Kabupaten Belu", ProvinceID: 22},
		{ID: 56, Name: "Kabupaten Bener Meriah", ProvinceID: 20},
		{ID: 57, Name: "Kabupaten Bengkalis", ProvinceID: 4},
		{ID: 58, Name: "Kabupaten Bengkayang", ProvinceID: 7},
		{ID: 59, Name: "Kota Bengkulu", ProvinceID: 6},
		{ID: 60, Name: "Kabupaten Bengkulu Selatan", ProvinceID: 6},
		{ID: 61, Name: "Kabupaten Bengkulu Tengah", ProvinceID: 6},
		{ID: 62, Name: "Kabupaten Bengkulu Utara", ProvinceID: 6},
		{ID: 63, Name: "Kabupaten Berau", ProvinceID: 15},
		{ID: 64, Name: "Kabupaten Biak Numfor", ProvinceID: 23},
		{ID: 65, Name: "Kabupaten Bima", ProvinceID: 21},
		{ID: 66, Name: "Kota Bima", ProvinceID: 21},
		{ID: 67, Name: "Kabupaten Bireuen", ProvinceID: 20},
		{ID: 68, Name: "Kabupaten Blitar", ProvinceID: 11},
		{ID: 69, Name: "Kota Blitar", ProvinceID: 11},
		{ID: 70, Name: "Kabupaten Blora", ProvinceID: 10},
		{ID: 71, Name: "Kabupaten Boalemo", ProvinceID: 19},
		{ID: 72, Name: "Kabupaten Bogor", ProvinceID: 9},
		{ID: 73, Name: "Kota Bogor", ProvinceID: 9},
		{ID: 74, Name: "Kabupaten Bojonegoro", ProvinceID: 11},
		{ID: 75, Name: "Kabupaten Bolaang Mongondow", ProvinceID: 28},
		{ID: 76, Name: "Kabupaten Bolaang Mongondow Selatan", ProvinceID: 28},
		{ID: 77, Name: "Kabupaten Bolaang Mongondow Timur", ProvinceID: 28},
		{ID: 78, Name: "Kabupaten Bolaang Mongondow Utara", ProvinceID: 28},
		{ID: 79, Name: "Kabupaten Bombana", ProvinceID: 24},
		{ID: 80, Name: "Kabupaten Bondowoso", ProvinceID: 11},
		{ID: 81, Name: "Kabupaten Bone", ProvinceID: 25},
		{ID: 82, Name: "Kabupaten Bone Bolango", ProvinceID: 19},
		{ID: 83, Name: "Kabupaten Boven Digoel", ProvinceID: 23},
		{ID: 84, Name: "Kabupaten Boyolali", ProvinceID: 10},
		{ID: 85, Name: "Kabupaten Brebes", ProvinceID: 10},
		{ID: 86, Name: "Kota Bukittinggi", ProvinceID: 29},
		{ID: 87, Name: "Kabupaten Buleleng", ProvinceID: 1},
		{ID: 88, Name: "Kabupaten Bulukumba", ProvinceID: 25},
		{ID: 89, Name: "Kabupaten Bulungan", ProvinceID: 16},
		{ID: 90, Name: "Kabupaten Bungo", ProvinceID: 8},
		{ID: 91, Name: "Kabupaten Buol", ProvinceID: 26},
		{ID: 92, Name: "Kabupaten Buru", ProvinceID: 18},
		{ID: 93, Name: "Kabupaten Buru Selatan", ProvinceID: 18},
		{ID: 94, Name: "Kabupaten Buton", ProvinceID: 24},
		{ID: 95, Name: "Kabupaten Buton Selatan", ProvinceID: 24},
		{ID: 96, Name: "Kabupaten Buton Tengah", ProvinceID: 24},
		{ID: 97, Name: "Kabupaten Buton Utara", ProvinceID: 24},
		{ID: 98, Name: "Kabupaten Ciamis", ProvinceID: 9},
		{ID: 99, Name: "Kabupaten Cianjur", ProvinceID: 9},
		{ID: 100, Name: "Kota Cilegon", ProvinceID: 3},
		{ID: 101, Name: "Kabupaten Cilacap", ProvinceID: 10},
		{ID: 102, Name: "Kota Cimahi", ProvinceID: 9},
		{ID: 103, Name: "Kabupaten Cirebon", ProvinceID: 9},
		{ID: 104, Name: "Kota Cirebon", ProvinceID: 9},
		{ID: 105, Name: "Kabupaten Dairi", ProvinceID: 31},
		{ID: 106, Name: "Kabupaten Deiyai", ProvinceID: 23},
		{ID: 107, Name: "Kabupaten Deli Serdang", ProvinceID: 31},
		{ID: 108, Name: "Kabupaten Demak", ProvinceID: 10},
		{ID: 109, Name: "Kabupaten Dharmasraya", ProvinceID: 29},
		{ID: 110, Name: "Kabupaten Dogiyai", ProvinceID: 23},
		{ID: 111, Name: "Kabupaten Dompu", ProvinceID: 21},
		{ID: 112, Name: "Kabupaten Donggala", ProvinceID: 26},
		{ID: 113, Name: "Kota Dumai", ProvinceID: 4},
		{ID: 114, Name: "Kabupaten Empat Lawang", ProvinceID: 12},
		{ID: 115, Name: "Kabupaten Ende", ProvinceID: 22},
		{ID: 116, Name: "Kabupaten Enrekang", ProvinceID: 25},
		{ID: 117, Name: "Kabupaten Fakfak", ProvinceID: 23},
		{ID: 118, Name: "Kabupaten Flores Timur", ProvinceID: 22},
		{ID: 119, Name: "Kabupaten Garut", ProvinceID: 9},
		{ID: 120, Name: "Kabupaten Gayo Lues", ProvinceID: 20},
		{ID: 121, Name: "Kabupaten Gianyar", ProvinceID: 1},
		{ID: 122, Name: "Kabupaten Gorontalo", ProvinceID: 19},
		{ID: 123, Name: "Kabupaten Gorontalo Utara", ProvinceID: 19},
		{ID: 124, Name: "Kota Gorontalo", ProvinceID: 19},
		{ID: 125, Name: "Kabupaten Gresik", ProvinceID: 11},
		{ID: 126, Name: "Kabupaten Grobogan", ProvinceID: 10},
		{ID: 127, Name: "Kabupaten Gunung Kidul", ProvinceID: 5},
		{ID: 128, Name: "Kabupaten Gunung Mas", ProvinceID: 14},
		{ID: 129, Name: "Kabupaten Halmahera Barat", ProvinceID: 30},
		{ID: 130, Name: "Kabupaten Halmahera Selatan", ProvinceID: 30},
		{ID: 131, Name: "Kabupaten Halmahera Tengah", ProvinceID: 30},
		{ID: 132, Name: "Kabupaten Halmahera Timur", ProvinceID: 30},
		{ID: 133, Name: "Kabupaten Halmahera Utara", ProvinceID: 30},
		{ID: 134, Name: "Kabupaten Hulu Sungai Selatan", ProvinceID: 13},
		{ID: 135, Name: "Kabupaten Hulu Sungai Tengah", ProvinceID: 13},
		{ID: 136, Name: "Kabupaten Hulu Sungai Utara", ProvinceID: 13},
		{ID: 137, Name: "Kabupaten Humbang Hasundutan", ProvinceID: 31},
		{ID: 138, Name: "Kabupaten Indragiri Hilir", ProvinceID: 4},
		{ID: 139, Name: "Kabupaten Indragiri Hulu", ProvinceID: 4},
		{ID: 140, Name: "Kabupaten Indramayu", ProvinceID: 9},
		{ID: 141, Name: "Kabupaten Intan Jaya", ProvinceID: 23},
		{ID: 142, Name: "Kabupaten Jayapura", ProvinceID: 23},
		{ID: 143, Name: "Kota Jayapura", ProvinceID: 23},
		{ID: 144, Name: "Kabupaten Jayawijaya", ProvinceID: 23},
		{ID: 145, Name: "Kabupaten Jember", ProvinceID: 11},
		{ID: 146, Name: "Kabupaten Jembrana", ProvinceID: 1},
		{ID: 147, Name: "Kabupaten Jeneponto", ProvinceID: 25},
		{ID: 148, Name: "Kabupaten Jepara", ProvinceID: 10},
		{ID: 149, Name: "Kabupaten Jombang", ProvinceID: 11},
		{ID: 150, Name: "Kota Kediri", ProvinceID: 11},
		{ID: 151, Name: "Kabupaten Kediri", ProvinceID: 11},
		{ID: 152, Name: "Kabupaten Keerom", ProvinceID: 23},
		{ID: 153, Name: "Kabupaten Kendal", ProvinceID: 10},
		{ID: 154, Name: "Kota Kendari", ProvinceID: 24},
		{ID: 155, Name: "Kabupaten Kepahiang", ProvinceID: 6},
		{ID: 156, Name: "Kabupaten Kepulauan Anambas", ProvinceID: 17},
		{ID: 157, Name: "Kabupaten Kepulauan Aru", ProvinceID: 18},
		{ID: 158, Name: "Kabupaten Kepulauan Mentawai", ProvinceID: 29},
		{ID: 159, Name: "Kabupaten Kepulauan Meranti", ProvinceID: 4},
		{ID: 160, Name: "Kabupaten Kepulauan Sangihe", ProvinceID: 28},
		{ID: 161, Name: "Kabupaten Kepulauan Seribu", ProvinceID: 6},
		{ID: 162, Name: "Kabupaten Kepulauan Siau Tagulandang Biaro", ProvinceID: 28},
		{ID: 163, Name: "Kabupaten Kepulauan Sula", ProvinceID: 30},
		{ID: 164, Name: "Kabupaten Kepulauan Talaud", ProvinceID: 28},
		{ID: 165, Name: "Kabupaten Kepulauan Tanimbar", ProvinceID: 18},
		{ID: 166, Name: "Kabupaten Kepulauan Yapen", ProvinceID: 23},
		{ID: 167, Name: "Kota Kupang", ProvinceID: 22},
		{ID: 168, Name: "Kabupaten Kupang", ProvinceID: 22},
		{ID: 169, Name: "Kabupaten Kutai Barat", ProvinceID: 15},
		{ID: 170, Name: "Kabupaten Kutai Kartanegara", ProvinceID: 15},
		{ID: 171, Name: "Kabupaten Kutai Timur", ProvinceID: 15},
		{ID: 172, Name: "Kabupaten Labuhan Batu", ProvinceID: 31},
		{ID: 173, Name: "Kabupaten Labuhan Batu Selatan", ProvinceID: 31},
		{ID: 174, Name: "Kabupaten Labuhan Batu Utara", ProvinceID: 31},
		{ID: 175, Name: "Kabupaten Lahat", ProvinceID: 12},
		{ID: 176, Name: "Kabupaten Lamandau", ProvinceID: 14},
		{ID: 177, Name: "Kabupaten Lamongan", ProvinceID: 11},
		{ID: 178, Name: "Kabupaten Lampung Barat", ProvinceID: 27},
		{ID: 179, Name: "Kabupaten Lampung Selatan", ProvinceID: 27},
		{ID: 180, Name: "Kabupaten Lampung Tengah", ProvinceID: 27},
		{ID: 181, Name: "Kabupaten Lampung Timur", ProvinceID: 27},
		{ID: 182, Name: "Kabupaten Lampung Utara", ProvinceID: 27},
		{ID: 183, Name: "Kabupaten Landak", ProvinceID: 7},
		{ID: 184, Name: "Kabupaten Langkat", ProvinceID: 31},
		{ID: 185, Name: "Kota Langsa", ProvinceID: 20},
		{ID: 186, Name: "Kabupaten Lanny Jaya", ProvinceID: 23},
		{ID: 187, Name: "Kabupaten Lebak", ProvinceID: 3},
		{ID: 188, Name: "Kabupaten Lebong", ProvinceID: 6},
		{ID: 189, Name: "Kabupaten Lembata", ProvinceID: 22},
		{ID: 190, Name: "Kabupaten Lima Puluh Kota", ProvinceID: 29},
		{ID: 191, Name: "Kabupaten Lingga", ProvinceID: 17},
		{ID: 192, Name: "Kabupaten Lombok Barat", ProvinceID: 21},
		{ID: 193, Name: "Kabupaten Lombok Tengah", ProvinceID: 21},
		{ID: 194, Name: "Kabupaten Lombok Timur", ProvinceID: 21},
		{ID: 195, Name: "Kabupaten Lombok Utara", ProvinceID: 21},
		{ID: 196, Name: "Kabupaten Lumajang", ProvinceID: 11},
		{ID: 197, Name: "Kabupaten Luwu", ProvinceID: 25},
		{ID: 198, Name: "Kabupaten Luwu Timur", ProvinceID: 25},
		{ID: 199, Name: "Kabupaten Luwu Utara", ProvinceID: 25},
		{ID: 200, Name: "Kabupaten Madiun", ProvinceID: 11},
		{ID: 201, Name: "Kota Madiun", ProvinceID: 11},
		{ID: 202, Name: "Kabupaten Magelang", ProvinceID: 10},
		{ID: 203, Name: "Kota Magelang", ProvinceID: 10},
		{ID: 204, Name: "Kabupaten Magetan", ProvinceID: 11},
		{ID: 205, Name: "Kabupaten Majalengka", ProvinceID: 9},
		{ID: 206, Name: "Kabupaten Majene", ProvinceID: 32},
		{ID: 207, Name: "Kabupaten Makassar", ProvinceID: 25},
		{ID: 208, Name: "Kota Makassar", ProvinceID: 25},
		{ID: 209, Name: "Kabupaten Malang", ProvinceID: 11},
		{ID: 210, Name: "Kota Malang", ProvinceID: 11},
		{ID: 211, Name: "Kabupaten Malinau", ProvinceID: 16},
		{ID: 212, Name: "Kabupaten Maluku Barat Daya", ProvinceID: 18},
		{ID: 213, Name: "Kabupaten Maluku Tengah", ProvinceID: 18},
		{ID: 214, Name: "Kabupaten Maluku Tenggara", ProvinceID: 18},
		{ID: 215, Name: "Kabupaten Maluku Tenggara Barat", ProvinceID: 18},
		{ID: 216, Name: "Kabupaten Mamasa", ProvinceID: 32},
		{ID: 217, Name: "Kabupaten Mamberamo Raya", ProvinceID: 23},
		{ID: 218, Name: "Kabupaten Mamberamo Tengah", ProvinceID: 23},
		{ID: 219, Name: "Kabupaten Mamuju", ProvinceID: 32},
		{ID: 220, Name: "Kabupaten Mamuju Tengah", ProvinceID: 32},
		{ID: 221, Name: "Kabupaten Mandailing Natal", ProvinceID: 31},
		{ID: 222, Name: "Kabupaten Manggarai", ProvinceID: 22},
		{ID: 223, Name: "Kabupaten Manggarai Barat", ProvinceID: 22},
		{ID: 224, Name: "Kabupaten Manggarai Timur", ProvinceID: 22},
		{ID: 225, Name: "Kabupaten Manokwari", ProvinceID: 23},
		{ID: 226, Name: "Kabupaten Manokwari Selatan", ProvinceID: 23},
		{ID: 227, Name: "Kota Manado", ProvinceID: 28},
		{ID: 228, Name: "Kabupaten Mappi", ProvinceID: 23},
		{ID: 229, Name: "Kabupaten Maros", ProvinceID: 25},
		{ID: 230, Name: "Kabupaten Marauke", ProvinceID: 23},
		{ID: 231, Name: "Kota Mataram", ProvinceID: 21},
		{ID: 232, Name: "Kabupaten Maybrat", ProvinceID: 23},
		{ID: 233, Name: "Kabupaten Melawi", ProvinceID: 7},
		{ID: 234, Name: "Kabupaten Merangin", ProvinceID: 8},
		{ID: 235, Name: "Kabupaten Merauke", ProvinceID: 23},
		{ID: 236, Name: "Kabupaten Meranti", ProvinceID: 4},
		{ID: 237, Name: "Kabupaten Mesuji", ProvinceID: 27},
		{ID: 238, Name: "Kota Metro", ProvinceID: 27},
		{ID: 239, Name: "Kabupaten Mimika", ProvinceID: 23},
		{ID: 240, Name: "Kabupaten Minahasa", ProvinceID: 28},
		{ID: 241, Name: "Kabupaten Minahasa Selatan", ProvinceID: 28},
		{ID: 242, Name: "Kabupaten Minahasa Tenggara", ProvinceID: 28},
		{ID: 243, Name: "Kabupaten Minahasa Utara", ProvinceID: 28},
		{ID: 244, Name: "Kabupaten Mojokerto", ProvinceID: 11},
		{ID: 245, Name: "Kota Mojokerto", ProvinceID: 11},
		{ID: 246, Name: "Kabupaten Morowali", ProvinceID: 26},
		{ID: 247, Name: "Kabupaten Morowali Utara", ProvinceID: 26},
		{ID: 248, Name: "Kabupaten Muara Enim", ProvinceID: 12},
		{ID: 249, Name: "Kabupaten Muaro Jambi", ProvinceID: 8},
		{ID: 250, Name: "Kabupaten Mukomuko", ProvinceID: 6},
		{ID: 251, Name: "Kabupaten Muna", ProvinceID: 24},
		{ID: 252, Name: "Kabupaten Muna Barat", ProvinceID: 24},
		{ID: 253, Name: "Kabupaten Murung Raya", ProvinceID: 14},
		{ID: 254, Name: "Kabupaten Musi Banyuasin", ProvinceID: 12},
		{ID: 255, Name: "Kabupaten Musi Rawas", ProvinceID: 12},
		{ID: 256, Name: "Kabupaten Musi Rawas Utara", ProvinceID: 12},
		{ID: 257, Name: "Kabupaten Nabire", ProvinceID: 23},
		{ID: 258, Name: "Kabupaten Nagan Raya", ProvinceID: 20},
		{ID: 259, Name: "Kabupaten Nagekeo", ProvinceID: 22},
		{ID: 260, Name: "Kabupaten Natuna", ProvinceID: 17},
		{ID: 261, Name: "Kabupaten Nduga", ProvinceID: 23},
		{ID: 262, Name: "Kabupaten Ngada", ProvinceID: 22},
		{ID: 263, Name: "Kabupaten Nganjuk", ProvinceID: 11},
		{ID: 264, Name: "Kabupaten Ngawi", ProvinceID: 11},
		{ID: 265, Name: "Kabupaten Nias", ProvinceID: 31},
		{ID: 266, Name: "Kabupaten Nias Barat", ProvinceID: 31},
		{ID: 267, Name: "Kabupaten Nias Selatan", ProvinceID: 31},
		{ID: 268, Name: "Kabupaten Nias Utara", ProvinceID: 31},
		{ID: 269, Name: "Kabupaten Nunukan", ProvinceID: 16},
		{ID: 270, Name: "Kabupaten Ogan Ilir", ProvinceID: 12},
		{ID: 271, Name: "Kabupaten Ogan Komering Ilir", ProvinceID: 12},
		{ID: 272, Name: "Kabupaten Ogan Komering Ulu", ProvinceID: 12},
		{ID: 273, Name: "Kabupaten Ogan Komering Ulu Selatan", ProvinceID: 12},
		{ID: 274, Name: "Kabupaten Ogan Komering Ulu Timur", ProvinceID: 12},
		{ID: 275, Name: "Kabupaten Pacitan", ProvinceID: 11},
		{ID: 276, Name: "Kabupaten Padang Lawas", ProvinceID: 31},
		{ID: 277, Name: "Kabupaten Padang Lawas Utara", ProvinceID: 31},
		{ID: 278, Name: "Kabupaten Padang Pariaman", ProvinceID: 29},
		{ID: 279, Name: "Kota Padang", ProvinceID: 29},
		{ID: 280, Name: "Kota Padang Panjang", ProvinceID: 29},
		{ID: 281, Name: "Kota Padangsidimpuan", ProvinceID: 31},
		{ID: 282, Name: "Kabupaten Pagar Alam", ProvinceID: 12},
		{ID: 283, Name: "Kabupaten Pakpak Bharat", ProvinceID: 31},
		{ID: 284, Name: "Kota Palangkaraya", ProvinceID: 14},
		{ID: 285, Name: "Kota Palembang", ProvinceID: 12},
		{ID: 286, Name: "Kabupaten Pamekasan", ProvinceID: 11},
		{ID: 287, Name: "Kabupaten Pandeglang", ProvinceID: 3},
		{ID: 288, Name: "Kabupaten Pangandaran", ProvinceID: 9},
		{ID: 289, Name: "Kabupaten Pangkajene Kepulauan", ProvinceID: 25},
		{ID: 290, Name: "Kabupaten Paniai", ProvinceID: 23},
		{ID: 291, Name: "Kabupaten Paser", ProvinceID: 15},
		{ID: 292, Name: "Kabupaten Pasaman", ProvinceID: 29},
		{ID: 293, Name: "Kabupaten Pasaman Barat", ProvinceID: 29},
		{ID: 294, Name: "Kabupaten Paser Utara", ProvinceID: 15},
		{ID: 295, Name: "Kabupaten Pasuruan", ProvinceID: 11},
		{ID: 296, Name: "Kota Pasuruan", ProvinceID: 11},
		{ID: 297, Name: "Kota Payakumbuh", ProvinceID: 29},
		{ID: 298, Name: "Kabupaten Pegunungan Arfak", ProvinceID: 23},
		{ID: 299, Name: "Kabupaten Pegunungan Bintang", ProvinceID: 23},
		{ID: 300, Name: "Kabupaten Pekalongan", ProvinceID: 10},
		{ID: 301, Name: "Kota Pekalongan", ProvinceID: 10},
		{ID: 302, Name: "Kabupaten Pelalawan", ProvinceID: 4},
		{ID: 303, Name: "Kota Pekanbaru", ProvinceID: 4},
		{ID: 304, Name: "Kabupaten Pemalang", ProvinceID: 10},
	}

	return DB.Create(&regencies).Error
}
